---

- name: update hosts file
  lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ item }}"
  with_items: "{{ hadoop_hosts }}"
  tags:
    - hadoop
    - hadoop:add:hosts

- name: create dirs
  file:
    dest: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - /opt/hadoop
    - /opt/hadoop_tmp
    - /opt/hadoop_tmp/hdfs
    - /opt/hadoop_tmp/hdfs/datanode
    - /opt/hadoop_tmp/hdfs/namenode
  tags:
    - hadoop
    - hadoop:dirs

- name: setup profile
  lineinfile:
    path: /home/pi/.bashrc
    state: present
    line: "{{ item }}"
  with_items:
    - alias ll="ls -lt"
    - export HADOOP_HOME=/opt/hadoop/hadoop
    - export PATH=$PATH:$HADOOP_HOME/bin
    - export PATH=$PATH:$HADOOP_HOME/sbin
    - export HADOOP_MAPRED_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_HOME=$HADOOP_HOME
    - export HADOOP_HDFS_HOME=$HADOOP_HOME
    - export YARN_HOME=$HADOOP_HOME
    - export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
    - export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"
    - export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre 
  tags:
    - hadoop
    - hadoop:profile

    