---
- name:	update apt and dist upgrade
  hosts: rpi
  become: True

  tasks:
  - name: update repos
    apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: upgrade dist
    apt:
      upgrade: dist
