---
- name: install and setup ftp 
  hosts: rpi
  become: True

  tasks:
  - name: clean apt
    apt:
      autoclean:  yes

  - name: update apt
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: install ftpd
    apt:  
      name: vsftpd
      state:  present
      allow_unauthenticated:  yes

  - name: create directory for FTP
    file:
      path: '/home/{{ ansible_user}}/FTP'
      state:  directory
      owner:  '{{ ansible_user }}'

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: anonymous_enable=NO

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: local_enable=YES

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: write_enable=YES

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: local_umask=077

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: 'local_root=/home/{{ ansible_user}}/FTP'

  - name: configure ftp
    lineinfile:
      path: /etc/vsftpd.conf
      line: 'accept_timeout=180'

  - name: restart service
    service:
      name: vsftpd
      state:  restarted

 
