---
- name: set hostnames 
  hosts: rpi
  become: True

  tasks:
  - name: set hostname
    hostname: 
      name: "{{ inventory_hostname }}"
    tags:
      - hostname
  - name: set timezone to Asia/Singapore
    timezone:
      name: Asia/Singapore
    tags:
      - timezone
  - name: set OS name for docker
    lineinfile:
      path: /etc/os-release
      regexp: 'ID=raspbian'
      line: 'ID=debian'
    tags:
      - os

 
