---
- name: set hostnames 
  hosts: rpi
  become: True

  tasks:
  - name: set hostname
    hostname: 
      name: "{{ inventory_hostname }}"
    tags:
      - hostname
  - name: set timezone to Asia/Singapore
    timezone:
      name: Asia/Singapore
    tags:
      - timezone

 
