---
- name: install and setup vnc 
  hosts: rpi
  become: True

  tasks:
  - name: update apt
    apt:
      autoclean:  yes
      update_cache: yes
      cache_valid_time: 3600

  - name: install vnc server
    apt:  
      name: realvnc-vnc-server
      state:  latest
      allow_unauthenticated:  yes

  - name: install vnc viewer
    apt:  
      name: realvnc-vnc-viewer
      state:  latest
      allow_unauthenticated:  yes

  - name: enable vnc
    command:  raspi-config nonint do_vnc 0
