---

- name: update repos
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - setup
    - setup:update
    - setup:update:repos

- name: upgrade dist
  apt:
    upgrade: dist
  tags:
    - setup
    - setup:update
    - setup:update:dist
