---

- name: set hostname
  hostname: 
    name: "{{ inventory_hostname }}"
  tags:
    - setup
    - setup:hostname

- name: set timezone to Asia/Singapore
  timezone:
    name: Asia/Singapore
  tags:
    - setup
    - setup:timezone

- name: set OS name for docker
  lineinfile:
    path: /etc/os-release
    regexp: 'ID=raspbian'
    line: 'ID=debian'
  tags:
    - setup
    - setup:osname

- name: expand file system
  command:  raspi-config nonint do_expand_rootfs
  tags:
    - setup
    - setup:expandfs